# ===== JobWatch Config (US-only, 7 days, sponsorship-aware) =====

keywords_any:
  - "data engineer"
  - "data engineering"
  - "analytics engineer"
  - "data analyst"
  - "data scientist"
  - "machine learning engineer"
  - "ml engineer"
  - "mlops"
  - "gen ai"
  - "generative ai"
  - "llm"
  - "ai engineer"
  # sponsorship signals
  - "visa sponsorship"
  - "h1b"
  - "work authorization"
  - "sponsor"
  - "opt"
  - "cpt"

must_have_any:
  - "python"
  - "sql"

exclude_if_title:
  - "senior"
  - "sr."
  - "staff"
  - "principal"
  - "director"
  - "vp"
  - "manager"
  - "executive assistant"
  - "recruiter"
  - "talent"
  - "marketing"
  - "sales"
  - "hr"
  - "design"
  - "product marketing"
  - "communications"

locations_any:
  - "united states"
  - "usa"
  - "u.s."
  - "remote - usa"
  - "us remote"

remote_ok: true
min_posted_days_ago: 7

companies_priority:
  - "databricks"
  - "snowflake"
  - "nvidia"
  - "microsoft"
  - "google"
  - "meta"
  - "amazon"
  - "stripe"
  - "openai"
  - "anthropic"
  - "huggingface"
  - "scaleai"
  - "palantir"
  - "datadog"
  - "uber"
  - "lyft"

sources:
  greenhouse_orgs:
    - "duolingo"
    - "remotecom"
    - "brex"

  lever_orgs:
    - "leverdemo"

  ashby_orgs:
    - "anthropic"
    - "openai"
    - "perplexityai"
    - "ramp"
    - "notion"
    - "airtable"
    - "figma"
    - "datadog"
    - "retool"

  workday_tenants:
    - { subdomain: "wd3", host: "relx", path: "relx", company: "RELX" }
    - { subdomain: "wd3", host: "lseg", path: "Careers", company: "LSEG" }
    - { subdomain: "wd5", host: "nvidia", path: "NVIDIAExternalCareerSite", company: "NVIDIA" }

  smartrec_companies:
    - "celonis"
    - "bumble"
    - "qualtrics"
    - "clari"

notify:
  telegram_bot_token: "${TELEGRAM_BOT_TOKEN}"
  telegram_chat_id: "${TELEGRAM_CHAT_ID}"
  slack_webhook_url: "${SLACK_WEBHOOK_URL}"