# ===== JobWatch Config (US-only, 7 days, sponsorship-aware) =====

# ---- Matching filters ----
keywords_any:
  - "data engineer"
  - "data engineering"
  - "analytics engineer"
  - "data analyst"
  - "data scientist"
  - "machine learning engineer"
  - "ml engineer"
  - "mlops"
  - "gen ai"
  - "generative ai"
  - "llm"
  - "ai engineer"
  # sponsorship signals
  - "visa sponsorship"
  - "h1b"
  - "work authorization"
  - "sponsor"
  - "opt"
  - "cpt"

must_have_any:
  - "python"
  - "sql"

exclude_if_title:
  - "director"
  - "vp"
  - "manager"
  - "principal"
  - "executive assistant"
  - "recruiter"
  - "talent"
  - "marketing"
  - "sales"
  - "hr"
  - "design"
  - "product marketing"
  - "communications"

# US-only (extra safety; code already detects state abbreviations)
locations_any:
  - "united states"
  - "usa"
  - "u.s."
  - "remote - usa"
  - "us remote"

# Optional: reduce staffing/consultancy noise by company name substring
company_deny_any:
  - "solutions"
  - "technologies"
  - "consulting"
  - "staffing"
  - "talent"
  - "tek"
  - "hexaware"
  - "mastech"
  - "insight global"
  - "ascendion"
  - "collabera"
  - "tata consultancy"
  - "infosys"
  - "wipro"
  - "hcl"

remote_ok: true
min_posted_days_ago: 7   # 7-day window

companies_priority:
  - "databricks"
  - "snowflake"
  - "nvidia"
  - "microsoft"
  - "google"
  - "meta"
  - "amazon"
  - "stripe"
  - "openai"
  - "anthropic"
  - "huggingface"
  - "scaleai"
  - "palantir"
  - "datadog"
  - "uber"
  - "lyft"

# ---- Sources to poll ----
sources:
  # Greenhouse (confirmed by your discover step)
  greenhouse_orgs:
    - "lyft"
    - "qualtrics"

  # SmartRecruiters (from your discover step)
  smartrec_companies:
    - "apple"
    - "cisco"
    - "expedia"
    - "google"
    - "ibm"
    - "meta"
    - "paypal"
    - "tesla"

  # Ashby (these may return 0 if the company moved ATS; safe to leave in)
  ashby_orgs:
    - "anthropic"
    - "openai"
    - "datadog"
    - "figma"
    - "notion"

  # Workday (explicit tenant URLs you provided/checked)
  workday_tenants:
    - tenant: "nvidia"
      company: "NVIDIA"
      url: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite"
    - tenant: "relx"
      company: "RELX"
      url: "https://relx.wd3.myworkdayjobs.com/en-US/relx"
    - tenant: "lseg"
      company: "LSEG"
      url: "https://lseg.wd3.myworkdayjobs.com/en-US/Careers"

# ---- Notifiers (env-driven) ----
notify:
  telegram_bot_token: "${TELEGRAM_BOT_TOKEN}"
  telegram_chat_id: "${TELEGRAM_CHAT_ID}"
  slack_webhook_url: "${SLACK_WEBHOOK_URL}"